### ISSUE TITLE
[Bug] Log-file/view doesn't show any progress

### ISSUE THREAD

**Issue by GitThisAcc** [TychoTheTaco/Twitch-Drops-Bot#125]
**Describe the bug**
The Log-View in 'Docker Desktop' doesn't show any progress in the log-view. Just empty lines.
If I check via [lazydocker](https://github.com/jesseduffield/lazydocker) there are those lines [screenshot].
This is just a visual bug.

**Screenshots**
![image](https://user-images.githubusercontent.com/13767589/172990873-371546e2-c7c6-4159-b070-3cb1a94613e4.png)

**Logs**
Attached Logs from Docker Desktop and Twitch-Drops-Bot
~~DockerDesktop_TwitchDrops.txt~~
~~Twitch-Drops-Bot.txt~~

**Docker config**
`docker-compose up -d`
my `docker-compose.yml`
```
version: '3.3'
services:
    tychothetaco:
        container_name: twitchdrops
        environment:
            - TZ=Europe/Berlin
        volumes:
            - 'D:/TwitchDrops:/app/data'
        image: ghcr.io/tychothetaco/twitch-drops-bot:latest
        restart: unless-stopped
```
